import Head from 'next/head'
import sty from "../node_modules/bootstrap/dist/css/bootstrap.min.css"
export default function Home() {
  return (
    <>
      <Head>
        <title>Scuttlr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href={sty} />

      </Head>
    </ >
  )
}
