import Head from 'next/head'
import Header from './../ui/header'
import Footer from './../ui/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

// link example with pathname and values as query  and also get the value of the query 

{/* <li>
<Link
  href={{
    pathname: '/about',
    query: { name: 'test' },
  }}
>
  About us
</Link>
</li> */}



// get the value of the query 

// import { useRouter } from 'next/router'

// const Post = () => {
//   const router = useRouter()
//   const { pid } = router.query

//   return <p>Post: {pid}</p>
// }

// export default Post



// styled component not loading 

// because the server-side rendering does not fetch the styles before rendering the page. 

// Next.js has the exact file you'll need to make this possible. Within the Next.js Github repo you can find _document.js. Within your Next.js project inside the pages folder create a file called _document.js and copy and paste all the code from the _document.js from the Next.js Github repo. This should fix your problem. Remember to restart the server to apply all changes.

// i added the file and now it works smoothly