import Head from 'next/head'
import Footer from '../ui/footer'
import Header from '../ui/header'
import { ThemeProvider } from 'styled-components'
import { myTheme } from '../theme'
export default function Home() {
  return (
    <>
      <Head>
        <title>Scuttlr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </ >
  )
}
